Spellchecker
parshikovalexey/achievementbot pull request #4
Opened 2017-08-17 12:05 UTC by DronKonstantin

Исправил код в соответствии со сделанными замечаниями

2017-08-21 00:57 UTC, Climber24 reviewed
В целом отличная работа, каких-либо серьезных ошибок я не нашел, мои комментарии в основном на тему code convention'а. Возможно, если бы у меня был опыт использования асинхронных методов, то нашел бы что-то, что стоит поменять. PR я бы одобрил, но пусть лучше посмотрит Алексей, поэтому просто использую Comment.

2017-08-21 00:57 UTC, Climber24 commented on BOTFirst/SpellChecker/Interfaces/ISpellChecker.cs
> +    interface ISpellChecker
Может быть стоит этот интерфейс тоже сделать абстрактным классом?
Из code convention'ов:
✓ DO name interfaces with adjective phrases, or occasionally with nouns or noun phrases.
Nouns and noun phrases should be used rarely and they might indicate that the type should be an abstract class, and not an interface.

2017-08-21 00:57 UTC, LaHesis commented on BOTFirst/SpellChecker/Classes/Mistake.cs
> +            Begin = begin;
Полагаю, что следует добавить this в конструкторе; понятно, что по идее можно не добавлять, но об этом пишут в code conventions, что это улучшает читабельность.

2017-08-21 00:57 UTC, LaHesis commented on BOTFirst/SpellChecker/Classes/SpellCheckerLT.cs
> +    public class SpellCheckerLT : ISpellChecker
Может быть SpellCheckerLT стоит сделать статичным классом?

2017-08-21 00:57 UTC, LaHesis commented on BOTFirst/SpellChecker/Classes/SpellCheckerLT.cs
> +        private string checkUrl; // URL для проверки текста
Я бы предложил сделать URL'ы readonly и переименовать checkUrl в urlForChecking, checkUrl лично у меня скорее ассоциируется с методом, чем с переменной.

2017-08-21 00:57 UTC, LaHesis commented on BOTFirst/SpellChecker/Classes/SpellCheckerLT.cs
> +        private string languagesresult; // строка(JSON) полученная от LanguageTool API при получении списка доступных языков
languagesResult?

2017-08-21 00:57 UTC, LaHesis commented on BOTFirst/SpellChecker/Classes/SpellCheckerLT.cs
> +    public class MistakeLT : Mistake
Не вынести ли MistakeLT в отдельный файл?

2017-08-21 00:57 UTC, LaHesis commented on BOTFirst/SpellChecker/Classes/SpellCheckerLT.cs
> +using Newtonsoft.Json.Linq;
В using Newtonsoft.Json.Linq; в SpellCheckerLT выдает ошибку, что нет Newtonsof, какой пакет нужно установить или какую ссылку добавить, чтобы ошибки не было?

2017-08-21 00:57 UTC, LaHesis commented on BOTFirst/SpellChecker/Classes/SpellCheckerLT.cs
> +        private Exception error; // дублирующее поле для хранения ошибки полученной при выполнении методов, любое исключение полученное в ходе выполнения метода окажется здесь
Может быть стоит переименовать error в checkerError или CheckerError? Т.к. в MistakeLT тоже есть error.

2017-08-21 00:57 UTC, LaHesis commented on BOTFirst/SpellChecker/Classes/SpellCheckerLT.cs
> +        public Exception Error { get { return error; } }
Вообще соответствующая приватная переменная свойства (error) по идее должна создаваться автоматически, поэтому ее скорее всего можно просто убрать (свойство будет public Exception Error { get; set; }), т.к. в get кроме возвращения переменной ничего нет. Хотя, если планируется, что туда будет добавлено еще что-то, то это другое дело конечно.

2017-08-21 00:57 UTC, LaHesis commented on BOTFirst/SpellChecker/Classes/SpellCheckerLT.cs
> +        /// <param name="match"></param>
Есть ли смысл в пустом теге?

2017-08-21 00:57 UTC, LaHesis commented on BOTFirst/SpellChecker/Classes/SpellCheckerLT.cs
> +            Position = new Position(offset, length);
Почему эта переменная с большой буквы, а переменные выше - с маленькой, ведь все они, если не ошибаюсь, приватные?

2017-08-21 00:57 UTC, LaHesis commented on BOTFirst/SpellChecker/Classes/SpellCheckerLT.cs
> +            Original = !String.IsNullOrEmpty(text) ? text.Substring(offset, length) : "";
Мое мнение - отрицание немного усложняет понимание, может быть лучше убрать его, а ветви тернарного оператора поменять местами?

2017-08-21 00:57 UTC, LaHesis commented on BOTFirst/SpellChecker/Classes/SpellCheckerLT.cs
> +        private List<Mistake> mistakes; // дублирующее поле содержащее список ошибок в проверенном тексте
Согласно code convention, все комментарии должны начинаться с большой буквы, заканчиваться точкой и располагаться на отдельной строке.

2017-08-21 00:57 UTC, LaHesis commented on BOTFirst/SpellChecker/Classes/SpellCheckerLT.cs
> +        private void GetAvailableLanguagesHandler(object sender, DownloadStringCompletedEventArgs e) // данный метод вызывается при срабатывании события асинхронной загрузки строки(DownloadStringComp
Полагаю, что лучше вынести комментарий в отдельную строку перед объявлением метода либо в документационный комментарий для метода + добавить точку и начинать комментарий с большой буквы, согласно code conventions.

2017-08-21 00:57 UTC, LaHesis commented on BOTFirst/SpellChecker/Classes/SpellCheckerLT.cs
> +        private void ParseCheck() // метод предназначен для парсинга реультата проверки текста
Возможно, что стоит переименовать ParseCheck() в ParseCheckResult() или ParseCheckingResult().

2017-08-21 00:57 UTC, LaHesis commented on BOTFirst/SpellChecker/Classes/SpellCheckerLT.cs
> +                        MistakeLT curMistake = new MistakeLT(match);
Если не ошибаюсь, рекомендуется не использовать сокращения, согласно code conventions, т.е. currentMistake. Хотя у меня в моем коде тоже есть несколько, типа Dic, но там имена длиннее и я на тот момент был не в курсе этого требования.

2017-08-21 00:57 UTC, LaHesis commented on BOTFirst/SpellChecker/Classes/SpellCheckerLT.cs
> +        public List<Mistake> Check(string language, string checkedText)
Предложил бы переименовать checkedText в checkingText или checkableText.

2017-08-21 00:57 UTC, LaHesis commented on BOTFirst/SpellChecker/Classes/SpellCheckerLT.cs
> +            return ""; // не реализован
Предлагаю использовать здесь в комментарии TODO или NOTE.

2017-08-21 00:57 UTC, LaHesis commented on BOTFirst/SpellChecker/Program.cs
> +            spellchkr.GetAvailableLanguagesAsync(); // получаем список языков(вернее только посылаем запрос)
Возможно, что сначала лучше подписаться, а потом сделать запрос?

2017-08-21 00:57 UTC, LaHesis commented on BOTFirst/SpellChecker/Program.cs
> +            Console.WriteLine("------------Ошибки---------------");
Предложил бы вынести этот код вывода ошибок, который повторяется или очень похож на код в случае асинхронной демонстрации, в отдельный метод.

2017-08-21 00:57 UTC, LaHesis commented on BOTFirst/SpellChecker/Program.cs
> +            {
Не должен ли здесь быть вывод исходного текста Console.WriteLine(text);, как в случае синхронной проверки? Либо, если вынести этот вывод результатов в отдельный метод, то вызов этого отдельного метода вместо несколько повторяющегося кода.

2017-08-21 05:26 UTC, parshikovalexey requested changes
@DronKonstantin, Костя. Я там набросал комментариев, которые нужно посмотреть. Плюс я там реализацию класса на более чистые методы (свободные от контекста). Хотел, чтобы ты посмотрел подход и его возможно обсудили.
По запросу на изменения: давай комментарии перенесем сверху, как @LaHesis  подметил, и у переменных сделаем var вместо типов. И вдогонку можно отшлифовать те вещи, которые @LaHesis упомянул

2017-08-21 05:26 UTC, parshikovalexey commented on BOTFirst/SpellChecker/Classes/SpellCheckerLT.cs
> +using Newtonsoft.Json.Linq;
Если проект не компилируется из ветки, и выдаются такие ошибки, то значит пакет не установлен. Нужно добавить его в проект, чтобы при развертывании на Азуре - не было проблем.

2017-08-21 05:26 UTC, parshikovalexey commented on BOTFirst/SpellChecker/Classes/SpellCheckerLT.cs
> +    public class SpellCheckerLT : ISpellChecker
@LaHesis, этот класс реализует интерфейс, а при использовании интерфейса - нам в любом случае придется делать явное/неявное создание экземпляра, который его будет реализовывать (то есть Static нецелесообразно)

2017-08-21 05:26 UTC, parshikovalexey commented on BOTFirst/SpellChecker/Classes/Mistake.cs
> +            Begin = begin;
Согласен, будет читабельнее.

2017-08-21 05:26 UTC, parshikovalexey commented on BOTFirst/SpellChecker/Classes/SpellCheckerLT.cs
> +        private List<Mistake> mistakes; // дублирующее поле содержащее список ошибок в проверенном тексте
+1. Комментарии, которые на отдельной строке и выше кода, к которому относятся - читаются намного лучше.

2017-08-21 05:26 UTC, parshikovalexey commented on BOTFirst/SpellChecker/Classes/SpellCheckerLT.cs
> +        private void GetAvailableLanguagesHandler(object sender, DownloadStringCompletedEventArgs e) // данный метод вызывается при срабатывании события асинхронной загрузки строки(DownloadStringComp
Для комментирования методов - использовать следует автоматическое документирование через ///. см тут: https://habrahabr.ru/post/41514/. Тут ты сразу и про метод опишешь и параметры также опишешь

2017-08-21 05:26 UTC, parshikovalexey commented on BOTFirst/SpellChecker/Classes/SpellCheckerLT.cs
> +        private void ParseCheck() // метод предназначен для парсинга реультата проверки текста
ParseCheckResult() - лучше

2017-08-21 05:26 UTC, parshikovalexey commented on BOTFirst/SpellChecker/Classes/SpellCheckerLT.cs
> +        public List<Mistake> Check(string language, string checkedText)
вообще можно и просто text. Из имени метода понятно, что делается проверка. Хотя лучше для метода имя будет - CheckText и тогда text -будет ок.

2017-08-21 05:26 UTC, parshikovalexey commented on BOTFirst/SpellChecker/Classes/SpellCheckerLT.cs
> +            Position = new Position(offset, length);
@LaHesis, Position - публичная в родительском классе

2017-08-21 05:26 UTC, parshikovalexey commented on BOTFirst/SpellChecker/Classes/SpellCheckerLT.cs
> +                JToken parsedJSON = JToken.Parse(languagesresult);
@DronKonstantin, я уже Сергею писал. Опять таки по code convention - если из правой части выражения понятно - какого типа должна быть переменная, то в c# рекомендуется использовать var вместо типа переменной.

2017-08-21 05:26 UTC, parshikovalexey commented on BOTFirst/SpellChecker/Interfaces/ISpellChecker.cs
> +    interface ISpellChecker
@DronKonstantin, @LaHesis. Объясню почему просил сделать это на интерфейсах. У интерфейсов и абстрактных классов есть общие черты, когда они оба описывают сигнатуры методов, которые должны быть реализованы в наследниках. Но при этом в абстрактном классе в самом можно сразу реализовать какой-то функционал, который будет использоваться в наследниках. Интерфейсы же только описывают то, что должно быть реализовано в наследниках. Второе большое различие. Класс может наследовать множество интерфейсов и реализовывать их, но может наследовать только один абстрактный класс.
Теперь к нашим задачам. Я предлагаю использовать интерфейсы для того, чтобы не использовать возможность чего-то там зашить в функционал самого асбстрактного класса, то есть сделать само описание интерфейса прозрачным и не опасаться появления внутри него каких-либо концов для возможных проблем. Во-вторых, как я покажу позднее, в проектах web-api есть возможность задать при формировании контекста выполнения приложения - определенные реализации интерфейса для описанных в проекте интерфейсов. И не нужно будет нигде в коде в конструкторах создавать экземпляры объектов. Для абстрактных классов - так сделать не получится.

2017-08-21 05:26 UTC, parshikovalexey commented on BOTFirst/SpellChecker/Program.cs
> +            Console.WriteLine("------------Ошибки---------------");
+1 для хорошего стиля программирования.

2017-08-21 09:30 UTC, DronKonstantin commented on BOTFirst/SpellChecker/Classes/SpellCheckerLT.cs
> +using Newtonsoft.Json.Linq;
Пакет так и называется Newtonsoft.JSON. Добавить его можно с помощью NuGet. Очень полезная библиотека, сильно упрощает работу с JSON, советую добавить в проект.

2017-08-21 09:30 UTC, DronKonstantin commented on BOTFirst/SpellChecker/Classes/Mistake.cs
> +            Begin = begin;
Добавлю

2017-08-21 09:32 UTC, DronKonstantin commented on BOTFirst/SpellChecker/Classes/SpellCheckerLT.cs
> +            Original = !String.IsNullOrEmpty(text) ? text.Substring(offset, length) : "";
Без проблем

2017-08-21 09:32 UTC, DronKonstantin commented on BOTFirst/SpellChecker/Classes/SpellCheckerLT.cs
> +        /// <param name="match"></param>
Он добавлен автоматически, я забыл убрать

2017-08-21 09:33 UTC, DronKonstantin commented on BOTFirst/SpellChecker/Classes/SpellCheckerLT.cs
> +                        MistakeLT curMistake = new MistakeLT(match);
Пусть будет currentMistake

2017-08-21 09:45 UTC, DronKonstantin commented on BOTFirst/SpellChecker/Classes/SpellCheckerLT.cs
> +                JToken parsedJSON = JToken.Parse(languagesresult);
JToken parsedJSON = JToken.Parse(languagesresult);
На мой взгляд тип переменной не слишком понятен из наименования метода.

2017-08-21 09:48 UTC, DronKonstantin commented on BOTFirst/SpellChecker/Classes/SpellCheckerLT.cs
> +        public Exception Error { get { return error; } }
https://docs.microsoft.com/ru-ru/dotnet/csharp/programming-guide/classes-and-structs/using-properties
В документации Microsoft рекомендуется создавать приватные переменные для свойств.

2017-08-21 09:53 UTC, DronKonstantin commented on BOTFirst/SpellChecker/Classes/SpellCheckerLT.cs
> +        public List<Mistake> Check(string language, string checkedText)
На мой взгляд checkedText будет корректным названием, так как это страдательный залог в английском, насколько я помню. Совсем корректным было бы textToBeChecked, но это слишком длинное название.

2017-08-21 09:55 UTC, DronKonstantin commented on BOTFirst/SpellChecker/Classes/SpellCheckerLT.cs
> +    public class MistakeLT : Mistake
Даже не знаю, думал об этом, но мне кажется тип ошибки всегда будет тесно связан с типом Чекера.

2017-08-21 09:59 UTC, DronKonstantin commented on BOTFirst/SpellChecker/Program.cs
> +            spellchkr.GetAvailableLanguagesAsync(); // получаем список языков(вернее только посылаем запрос)
Пожалуй, что так.

2017-08-21 10:00 UTC, DronKonstantin commented on BOTFirst/SpellChecker/Program.cs
> +            {
Я делал методы демонстрации на скорую руку, только чтобы продемонстрировать работу класса. Все верно, стоит вынести вывод в отдельный метод.

2017-08-21 10:44 UTC, LaHesis commented on BOTFirst/SpellChecker/Classes/SpellCheckerLT.cs
> +        public Exception Error { get { return error; } }
Ок

2017-08-21 10:46 UTC, LaHesis commented on BOTFirst/SpellChecker/Classes/SpellCheckerLT.cs
> +        public List<Mistake> Check(string language, string checkedText)
Чтобы бы был страдательный, нужна to be, а просто checked перед существительным будет лишь как прилагательное (https://www.multitran.ru/c/m.exe?CL=1&l1=1&s=checked) и переводиться это будет как "проверенный текст", что не совсем корректно, ведь мы подаем не проверенный, а проверяемый текст. Еще один вариант можно предложить - textForChecking. Либо просто text, как предлагает Алексей.

2017-08-21 11:02 UTC, LaHesis commented on BOTFirst/SpellChecker/Classes/SpellCheckerLT.cs
> +        public Exception Error { get { return error; } }
Ок, почитаю.

2017-08-22 02:15 UTC, parshikovalexey commented on BOTFirst/SpellChecker/Classes/SpellCheckerLT.cs
> +                JToken parsedJSON = JToken.Parse(languagesresult);
@DronKonstantin, ок тогда. Мне было понятно какой тип, поэтому и привел комментарий здесь

2017-08-22 02:24 UTC, parshikovalexey commented on BOTFirst/SpellChecker/Classes/SpellCheckerLT.cs
> +        public List<Mistake> Check(string language, string checkedText)
@DronKonstantin, @LaHesis, на самом деле - наша любовь к таким длинным параметрам(сам этим периодически страдаю) - приводит вот к таким дискуссиям. Если говорить с точки зрения английского, то checkedText - действительно "проверенный текст". И поэтому я предлагаю пытаться переходить к стилю, в котором не нужно будет делать таких имен, а именно - имя метода обозначает конкретное действие, а параметры описывают элементы, над которыми будет проводиться работа. Посмотрите на https://msdn.microsoft.com/ru-ru/library/1k20k614(v=vs.110).aspx и https://msdn.microsoft.com/ru-ru/library/essfb559(v=vs.110).aspx. Из имени метода понятно, что будет делаться - конвертироваться туда-то, или парситься туда-то. И параметры здесь без дополнительной информации - ParsedValue - нет, как нет и ValueToBeConverted. Просто значение. Поэтому и предлагаю вариант с именованием CheckText - проверить текст, а параметр просто text.

2017-08-22 02:29 UTC, parshikovalexey commented on BOTFirst/SpellChecker/Classes/SpellCheckerLT.cs
> +    public class MistakeLT : Mistake
@DronKonstantin, здесь скорее всего для @LaHesis играет роль рекомендация - каждый класс определять в отдельном файле. Это имеет место по той причине, что при разделении классов по отдельным файлам - мы получаем возможность разделять друг от друга разнородного типа объекты. Если MistakeLT - описывает модель, которая представляет сущность данных, то SpellCheckerLT - это уже сервис, который выполняет функциональные операции над данными (если позволите - контроллер в модели MVC). 
С другой стороны, @DronKonstantin скорее всего имеет ввиду, что MistakeLT - необходимая часть для SpellCheckerLT и является его составляющей, поэтому здесь и размещается.
Мое мнение - модели данных нужно отделять и переносить в отдельный файл.

2017-08-25 18:40 UTC, LaHesis commented on BOTFirst/SpellChecker/Classes/SpellCheckerLT.cs
> +        private readonly string checkUrl; // URL для проверки текста
Здесь и еще в нескольких местах - согласно code conventions, комментарии должны располагаться на отдельной строке, начинаться с большой буквы и заканчиваться точкой. Поправь, если не трудно.

2017-08-28 07:28 UTC, DronKonstantin commented on BOTFirst/SpellChecker/Classes/SpellCheckerLT.cs
> +        private readonly string checkUrl; // URL для проверки текста
Исправлено

2017-08-28 10:00 UTC, LaHesis commented on BOTFirst/SpellChecker/Classes/SpellCheckerLT.cs
> +using Newtonsoft.Json.Linq;
Причина была в версии студии, на 2015ой все норм, а на 2017ой выдает, что нет пространства имен.

2017-08-29 03:15 UTC, parshikovalexey approved these changes

2017-08-29 03:15 UTC, merged